---
- name: Shutdown guests
  hosts: site
  tasks:
    - name: Load the variables
      ansible.builtin.include_vars:
        dir: vars
        extensions: [yml]
    - name: Shutdown guests
      ansible.builtin.include_role:
        name: shutdown_guests
    - name: Notify health check
      ansible.builtin.include_role:
        name: health_check
    - name: Shutdown host
      ansible.builtin.include_role:
        name: shutdown_host
