- name: List containers
  community.docker.docker_host_info:
    containers: true
  register: result

- name: Start containers
  community.docker.docker_container:
    name: "{{ item.Id }}"
    state: started
  with_items: "{{ result.containers }}"