---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Check if system needs a restart
  command: "needs-restarting -r || true"
  register: restart_needed
  changed_when: false

- name: Restart the machine if required
  command: "reboot"
  async: 0
  poll: 0
  when: restart_needed.stdout != "0"
