- name: "Update apt-cache and do dist upgrade"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
  sudo: yes

- name: "Check if reboot required"
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  sudo: yes

- name: "Reboot if required"
  reboot:
  when: reboot_required_file.stat.exists == true
  sudo: yes