---
- name: apt update
  apt:
    update_cache: yes
  sudo: yes

- name: apt dist upgrade
  apt:
    upgrade: dist
  sudo: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  sudo: yes

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
  sudo: yes
