---
- name: apt update
  apt:
    update_cache: yes

- name: apt dist upgrade
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Execute restart script if container_restart_script is set
  command: "{{ container_restart_script }}"
  when: container_restart_script | default(false) != false

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
