- name: Create the backup directory
  ansible.builtin.file:
    path: /mnt/backup
    state: directory

- name: Create the system directory (for the disk volume)
  ansible.builtin.file:
    path: /mnt/system
    state: directory

- name: Mount the disk volume to the system directory
  ansible.posix.mount:
    path: "{{ vm_source }}"
    src: /mnt/system
    opts: bind
    state: mounted
    fstype: none

- name: Mount the NFS share
  ansible.posix.mount:
    src: "{{ vm_target }}"
    path: /mnt/backup
    state: mounted
    fstype: nfs

- name: Rsync to NFS Share
  ansible.posix.synchronize:
    src: /mnt/system/
    dest: /mnt/backup
    rsync_opts:
      - "--exclude=/dev/*"
      - "--exclude=/proc/*"
      - "--exclude=/sys/*"
      - "--exclude=/run/*"
      - "--exclude=/mnt/*"
      - "--exclude=/media/*"
      - "--exclude=swapfile"
      - "--exclude=lost+found"
      - "--exclude=.cache"

- name: Unmount the nfs share
  ansible.posix.mount:
    path: /mnt/backup
    state: unmounted

- name: Unmount the disk volume
  ansible.posix.mount:
    path: /mnt/system
    state: unmounted
