- name: List containers
  community.docker.docker_host_info:
    containers: true
  register: result

- name: Stop containers
  community.docker.docker_container:
    name: "{{ item.Id }}"
    state: stopped
  loop: result.containers