- name: Get info on docker host and list containers
  community.docker.docker_host_info:
    containers: true
  register: result

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2  